<a href="https://colab.research.google.com/github/zohyan/Understanding-PyTorch/blob/master/What_is_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[6.8704e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0705, 0.9918, 0.4756],
        [0.2424, 0.5560, 0.5036],
        [0.2889, 0.3502, 0.1404],
        [0.4699, 0.9838, 0.0836],
        [0.0084, 0.2540, 0.8445]])


Construct a matrix filled zeros and of dtype long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Create a tensor based on an existing tensor

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)                            

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0347,  0.3618, -1.9129],
        [ 0.1664, -0.2573,  0.1651],
        [-1.2921,  1.1335, -0.5478],
        [-1.8872,  0.5193,  0.2043],
        [ 1.8846,  0.0660, -1.0994]])


Get its size:

In [7]:
print(x.size())

torch.Size([5, 3])


# Operations

Addition: syntax 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.5386,  0.6751, -1.4217],
        [ 1.0629, -0.2043,  1.0474],
        [-1.1375,  1.6853, -0.1326],
        [-1.3614,  0.6386,  1.1564],
        [ 2.2335,  0.3055, -0.1546]])


Addition: syntax 2

In [9]:
print(torch.add(x, y))

tensor([[ 1.5386,  0.6751, -1.4217],
        [ 1.0629, -0.2043,  1.0474],
        [-1.1375,  1.6853, -0.1326],
        [-1.3614,  0.6386,  1.1564],
        [ 2.2335,  0.3055, -0.1546]])


Addition: providing an output tensor as argument

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.5386,  0.6751, -1.4217],
        [ 1.0629, -0.2043,  1.0474],
        [-1.1375,  1.6853, -0.1326],
        [-1.3614,  0.6386,  1.1564],
        [ 2.2335,  0.3055, -0.1546]])


Addition: in-place

In [11]:
y.add_(x)
print(y)

tensor([[ 1.5386,  0.6751, -1.4217],
        [ 1.0629, -0.2043,  1.0474],
        [-1.1375,  1.6853, -0.1326],
        [-1.3614,  0.6386,  1.1564],
        [ 2.2335,  0.3055, -0.1546]])


Resizing : If you want to resize/reshape tensor, you can use torch.view

In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use .item() to get the value as a Python number

In [13]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3159])
0.3159102201461792


# NumPy Bridge

Converting a Torch Tensor to a NumPy Array

In [0]:
a = torch.ones(5)
b = a.numpy()

Converting NumPy Array to Torch Tensor

In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)